name: gold_coin_manager
description: مدیریت دارایی طلا و سکه با دریافت قیمت آنلاین
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  fl_chart: ^0.69.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  
  # اضافه کردن پوشه assets
  assets:
    - assets/fonts/
    # اگر بعداً عکس یا آیکون اضافه کردی می‌تونی اینجا اضافه کنی
    # - assets/images/
  
  # اضافه کردن فونت Vazir
  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf
          weight: 400
        # اگر نسخه‌های دیگه فونت رو هم داری، می‌تونی اضافه کنی
        # - asset: assets/fonts/Vazir-Bold.ttf
        #   weight: 700
        # - asset: assets/fonts/Vazir-Light.ttf
        #   weight: 300
        # - asset: assets/fonts/Vazir-Medium.ttf
        #   weight: 500
