name: Nokhodgram
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.1.0
  dio: ^5.4.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  image_cropper: ^5.0.1
  # image_editor را موقتاً حذف می‌کنیم تا تداخل ImageSource برطرف شود
  # video_editor: ^2.4.0  # در صورت نیاز می‌توانید اضافه کنید
  video_player: ^2.8.1
  just_audio: ^0.9.36
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  permission_handler: ^11.0.1
  connectivity_plus: ^5.0.2
  flutter_staggered_animations: ^1.1.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  google_fonts: ^4.0.4   # نسخه پایدارتر (بدون خطای کامپایل)
  flutter_svg: ^2.0.9
  animations: ^2.0.8
  flutter_dotenv: ^5.1.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true