name: tweeter_client
description: A Flutter client for the Tweeter server.
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod:
  # Networking
  dio:
  # Storage
  shared_preferences:
  # Image & file picking
  image_picker:
  file_picker:
  # Image caching
  cached_network_image:
  # Media playback
  video_player:
  just_audio:
  # File handling
  path_provider:
  open_file:
  flutter_riverpod:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true