# pubspec.yaml
name: gold_coin_manager
description: مدیریت دارایی طلا و سکه با دریافت قیمت آنلاین
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0
  fl_chart: ^0.69.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  # assets:
  #   - fonts/  # اگر فونت فارسی دارید