name: Nokhodgram
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  http: ^1.1.0
  dio: ^5.3.2
  image_picker: ^1.0.4
  file_picker: ^8.0.0
  path_provider: ^2.1.0
  image_cropper: ^5.0.0
  image_editor: ^1.3.0
  video_editor: ^3.0.0
  video_player: ^2.7.1
  just_audio: ^0.9.35
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0
  permission_handler: ^10.4.3
  connectivity_plus: ^4.0.1
  flutter_staggered_animations: ^1.1.0
  shimmer: ^3.0.0
  intl: ^0.18.1
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  animations: ^2.0.8
  flutter_dotenv: ^5.1.0
  lottie: ^2.6.0
  ffmpeg_kit_flutter_min_gpl: ^6.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true