# pubspec.yaml
name: tweeter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  http:
  provider:
  shared_preferences:
  image_picker:
  video_player:
  audioplayers:
  cached_network_image:
  intl:
  flutter_staggered_animations:
  photo_view:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true